{% set version = "0.1.2" %}

package:
  name: pbcuda
  version: {{ version }}

source:
  url: https://github.com/lijun99/pbcuda/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 72efca5ea46a1ec4877b52eac3d1b55ba07acfca1935285a34b3749e626bbd6f

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  number: 0
  skip: true  # [cuda_compiler_version == "None" or osx or win]

requirements:
  build:
    - cmake
    - make
    - pybind11
    - ninja
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}

  host:
    - python
    - pybind11
    - pip
    - setuptools
    - scikit-build
    - cuda-version {{ cuda_compiler_version }}

  run:
    - python

test:
  imports:
    - pbcuda
  commands:
    - python -c "import pbcuda; print('Success')"

about:
  home: https://github.com/lijun99/pbcuda
  summary: 'A Python Interface to CUDA with pybind11'
  description: |
    pbcuda - a Python interface to CUDA libraries and routines using pybind11. 
    It simplifies hybrid Python/C++/CUDA development by providing seamless bindings 
    to CUDA functionalities, enabling efficient and flexible development workflows 
    for high-performance computing and GPU-accelerated applications.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lijun99
